import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { URL } from 'node:url'

const root = new URL('../', import.meta.url)
const readJson = async (path) => JSON.parse(await readFile(new URL(path, root), 'utf8'))
const [primitives, light, dark] = await Promise.all([
  readJson('src/tokens.json'),
  readJson('src/themes/light.json'),
  readJson('src/themes/dark.json'),
])

function flatten(value, path = [], inheritedType) {
  const type = value?.$type ?? inheritedType
  if (value && typeof value === 'object' && '$value' in value) return [{ path, type, value: value.$value }]
  return Object.entries(value ?? {})
    .filter(([key]) => !key.startsWith('$'))
    .flatMap(([key, child]) => flatten(child, [...path, key], type))
}

const primitiveEntries = flatten(primitives)
const primitiveMap = new Map(primitiveEntries.map((entry) => [entry.path.join('.'), entry]))

function resolveValue(value, stack = []) {
  if (typeof value !== 'string' || !/^\{.+\}$/.test(value)) return value
  const reference = value.slice(1, -1)
  if (stack.includes(reference)) throw new Error(`Circular token alias: ${[...stack, reference].join(' -> ')}`)
  const target = primitiveMap.get(reference)
  if (!target) throw new Error(`Unknown token alias: ${reference}`)
  return resolveValue(target.value, [...stack, reference])
}

const unit = (value) => `${value.value}${value.unit}`
function cssValue(value, type) {
  const resolved = resolveValue(value)
  if (type === 'dimension' || type === 'duration') return unit(resolved)
  if (type === 'fontFamily') return resolved.map((item) => item.includes(' ') ? `"${item}"` : item).join(', ')
  if (type === 'cubicBezier') return `cubic-bezier(${resolved.join(', ')})`
  if (type === 'shadow') return `${unit(resolved.offsetX)} ${unit(resolved.offsetY)} ${unit(resolved.blur)} ${unit(resolved.spread)} ${resolved.color}`
  return String(resolved)
}

const cssName = (path) => `--li-${path.join('-').replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`)}`
const declarations = (entries) => entries
  .sort((a, b) => a.path.join('.').localeCompare(b.path.join('.')))
  .map((entry) => `  ${cssName(entry.path)}: ${cssValue(entry.value, entry.type)};`)
  .join('\n')

const lightEntries = flatten(light)
const darkEntries = flatten(dark)
const css = `/* Generated by @lithium/tokens. Do not edit. */\n:root {\n${declarations([...primitiveEntries, ...lightEntries])}\n}\n\n[data-theme="dark"] {\n${declarations(darkEntries)}\n}\n`
const published = { schemaVersion: 1, primitives, themes: { light, dark } }
const figmaVariables = {
  schemaVersion: 1,
  collection: 'Lithium',
  modes: ['light', 'dark'],
  variables: lightEntries.map((entry) => {
    const path = entry.path.join('.')
    const darkEntry = darkEntries.find((candidate) => candidate.path.join('.') === path)
    if (!darkEntry) throw new Error(`Dark theme is missing ${path}`)
    return {
      name: path.replaceAll('.', '/'),
      type: entry.type,
      values: { light: resolveValue(entry.value), dark: resolveValue(darkEntry.value) },
    }
  }),
}

await mkdir(new URL('dist/', root), { recursive: true })
await Promise.all([
  writeFile(new URL('dist/theme.css', root), css),
  writeFile(new URL('dist/tokens.json', root), `${JSON.stringify(published, null, 2)}\n`),
  writeFile(new URL('dist/figma-variables.json', root), `${JSON.stringify(figmaVariables, null, 2)}\n`),
  writeFile(new URL('dist/tokens.d.ts', root), 'declare const tokens: Record<string, unknown>\nexport default tokens\n'),
])
